/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/signalmap/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SignalMap events with filters */
        get: operations["listSignalMapEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signalmap/event/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single SignalMap event by ID */
        get: operations["getSignalMapEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signalmap/source-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get source health for all SignalMap data providers */
        get: operations["getSignalMapSourceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signalmap/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE stream of live SignalMap events */
        get: operations["streamSignalMapEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signalmap/brief/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get AI-generated global SignalMap brief (cached) */
        post: operations["getSignalMapGlobalBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signalmap/brief/event/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get AI-generated why-it-matters brief for a specific event (cached) */
        post: operations["getSignalMapEventBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignalMapEvent: {
            id: string;
            category: components["schemas"]["SignalMapCategory"];
            severity: components["schemas"]["SignalMapSeverity"];
            title: string;
            summary: string;
            tags: string[];
            startedAt?: string;
            endedAt?: string;
            lastObservedAt: string;
            locations: components["schemas"]["SignalMapLocation"][];
            sources: components["schemas"]["SignalMapSource"][];
            confidence: number;
            provider?: string;
            kind: components["schemas"]["SignalMapKind"];
            watchlistMatch: boolean;
            markerEligible: boolean;
        };
        /** @enum {string} */
        SignalMapCategory: "internet" | "provider" | "technology" | "finance" | "geopolitics" | "conflict" | "cyber" | "climate" | "health" | "energy" | "supply_chain" | "infrastructure";
        /** @enum {string} */
        SignalMapSeverity: "critical" | "high" | "medium" | "low" | "info";
        SignalMapLocation: {
            name: string;
            countryIso2?: string;
            lat?: number;
            lon?: number;
            scope: components["schemas"]["SignalMapLocationScope"];
            confidence: number;
            evidence?: string;
        };
        /** @enum {string} */
        SignalMapLocationScope: "city" | "region" | "country" | "network" | "provider" | "unknown";
        SignalMapSource: {
            id: string;
            label: string;
            url?: string;
            tier?: number;
            verified?: boolean;
            fetchedAt?: string;
        };
        /** @enum {string} */
        SignalMapKind: "radar_outage" | "radar_anomaly" | "provider_status" | "story";
        SignalMapSourceHealth: {
            id: string;
            label: string;
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            fetchedAt: number;
            eventCount: number;
            detail: string;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSignalMapEvents: {
        parameters: {
            query?: {
                start_ms?: number;
                end_ms?: number;
                categories?: string[];
                watch_regions?: string[];
                watch_providers?: string[];
                watchlist_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered SignalMap events with source health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["SignalMapEvent"][];
                        sourceHealth: components["schemas"]["SignalMapSourceHealth"][];
                        fetchedAt: number;
                        upstreamUnavailable: boolean;
                    };
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSignalMapEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SignalMap event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalMapEvent"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSignalMapSourceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source health summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sourceHealth: components["schemas"]["SignalMapSourceHealth"][];
                        fetchedAt: number;
                    };
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    streamSignalMapEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume SSE stream from a previously received event ID */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream (text/event-stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Replay ID was evicted — client must re-fetch from scratch */
            204: {
                headers: {
                    "X-Replay-Lost": boolean;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSignalMapGlobalBrief: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Global brief with bullet points and sources */
            200: {
                headers: {
                    "X-Cache": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bullets: string[];
                        generatedAt: string;
                        model: string;
                        sources: {
                            label: string;
                            url: string;
                        }[];
                        lastGeneratedAt?: string;
                    };
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSignalMapEventBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Event brief with why-it-matters explanation */
            200: {
                headers: {
                    "X-Cache": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        whyItMatters: string;
                        model: string;
                        generatedAt: string;
                    };
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
